// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuubT1yeI9klipVUBaOSa41sggdtNaquU',
    appId: '1:377225079315:web:4118af19849fd78a116de6',
    messagingSenderId: '377225079315',
    projectId: 'mile-tasks',
    authDomain: 'mile-tasks.firebaseapp.com',
    storageBucket: 'mile-tasks.appspot.com',
    measurementId: 'G-EXLMQQLEJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBMY4Oi6Uo0AJgdG_ICClF-k1_kin8XEY',
    appId: '1:377225079315:android:b5821dab384e482d116de6',
    messagingSenderId: '377225079315',
    projectId: 'mile-tasks',
    storageBucket: 'mile-tasks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA1a8DPwP6VMspXnlZgebDwBWt_tXKabM',
    appId: '1:377225079315:ios:a3e1bdca3e1884a0116de6',
    messagingSenderId: '377225079315',
    projectId: 'mile-tasks',
    storageBucket: 'mile-tasks.appspot.com',
    iosClientId: '377225079315-ujodem0n2g3at8sle8i8ic633l57hqk1.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA1a8DPwP6VMspXnlZgebDwBWt_tXKabM',
    appId: '1:377225079315:ios:640fb30d5d5ea66a116de6',
    messagingSenderId: '377225079315',
    projectId: 'mile-tasks',
    storageBucket: 'mile-tasks.appspot.com',
    iosClientId: '377225079315-brnadhka4t732f9dml8oc1a6876qc9bq.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloworld.RunnerTests',
  );
}
